var lowerLetters = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"];
var upperLetters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"];
var specialChar = ["!", "@", "#", "$", "%", "^", "&", "?", "_", "-", "+", "=", "~"]
var numbers = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]

var password = []

//what do I want to do?
//ask user questions:
//do you want lowercase
//do you want uppercase
//do you want numbers
//do you want special characters

//how long do you want the password

//any no answer means that these cannot be included
//true-false?

//then need to generate password from remaining choices or all
//need to go through loop for number of times person wants password generated by length
//need to eliminate what wasn't selected
//need to check to see if anything was selected
//for loop

//then need to push characters to the array
//then need to print out result so user can see it on web page