var lowerLetters = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"];
var upperLetters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"];
var specialChar = ["!", "@", "#", "$", "%", "^", "&", "?", "_", "-", "+", "=", "~"]
var numbers = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]

var passwordLength = 

var master = []

if (upperInputChecked) {
for (var 1 = 0; i < upperLetters.length; i++) {

    master.push(upperLetters[i])
    }
//do this for each array
//upper input checked would be the radial button checked, I did this differently
}

for (var = 0; i < passwordLength; i++) {

    var randomIndex = Math.floor(Math.random() * master.length)
    password = password + master[randomIndex]
}

//math.random only returns a number between 0 and 1
//mutiply by 10 to get a number above 1



var password = ""

//what do I want to do?
//ask user questions: event listener
//do you want lowercase
var lowerCase = confirm("Do you want lowercase letters?");
//do you want uppercase
var upperCase = confirm("Do you want uppercase letters?");
//do you want numbers
var numerical = confirm("Do you want numbers?");
//do you want special characters
var special = confirm("Do you want special characters?");

//how long do you want the password
var length = prompt("How many characters do you want in your password?  Select between 8 and 128 characters.");
console.log(length)
//how to test for length?
//length < 8 return error
//length > 128 also error

//event listeners

//any no answer means that these cannot be included
//true-false?

//then need to generate password from remaining choices or all
//need to go through loop for number of times person wants password generated by length?
//need to eliminate what wasn't selected
//need to check to see if anything was selected
//for loop?
function generatePassword () {

if (lowerCase === true && upperCase === true && numerical === true && special === true) {
  $("#submit").on("click", function() {
        for (var i = 0; i <= length; i++) {
        var character = Math.floor(Math.random() * arraylength);
        password = character + password;
//but how to get it to pick an array first to get the character from?
    }

          } else if (lowerCase === false && upperCase === true && numerical === true && special === true) {
            //little less magic here

            //how to eliminate array?
            
          } else if (lowerCase === true && upperCase === false && numerical === true && special === true){
            //little less magic here

          } else if (lowerCase === true && upperCase === true && numerical === false && special === true){
            //little less magic here

          } else if (lowerCase === true && upperCase === true && numerical === true && special === false){
            //little less magic here

          } else if (lowerCase === true && upperCase === false && numerical === true && special === true){
            //little less magic here

          } else if (lowerCase === false && upperCase === false && numerical === true && special === true){
            //little less magic here

          } else if (lowerCase === false && upperCase === true && numerical === false && special === true){
            //little less magic here

          } else if (lowerCase === false && upperCase === true && numerical === true && special === false){
            //little less magic here

          } else if (lowerCase === true && upperCase === false && numerical === false && special === true){
            //little less magic here

          } else if (lowerCase === true && upperCase === false && numerical === true && special === false){
            //little less magic here

          } else if (lowerCase === true && upperCase === true && numerical === false && special === false){
            //little less magic here

          } else if (lowerCase === false && upperCase === false && numerical === false && special === true){
            //even less magic here

          } else if (lowerCase === false && upperCase === false && numerical === true && special === false){
            //even less magic here

          } else if (lowerCase === false && upperCase === true && numerical === false && special === false){
            //even less magic here

          } else if (lowerCase === true && upperCase === false && numerical === false && special === false){
            //even less magic here

          } else (lowerCase === false && upperCase === false && numerical === false && special === false){
            return;

          }


//then need to push characters to the array
generatePassword.push(password);
        }
//then need to post result so user can see it on web page