var lowerLetters = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"];
var upperLetters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"];
var specialChar = ["!", "@", "#", "$", "%", "^", "&", "?", "_", "-", "+", "=", "~"]
var numbers = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]

var password = []

//what do I want to do?
//ask user questions:
//do you want lowercase
var lowerCase = confirm("Do you want lowercase letters?");
//do you want uppercase
var upperCase = confirm("Do you want uppercase letters?");
//do you want numbers
var numerical = confirm("Do you want numbers?");
//do you want special characters
var special = confirm("Do you want special characters?");

//how long do you want the password
var length = prompt("How many characters do you want in your password?");

//any no answer means that these cannot be included
//true-false?

//then need to generate password from remaining choices or all
//need to go through loop for number of times person wants password generated by length?
//need to eliminate what wasn't selected
//need to check to see if anything was selected
//for loop?
if (lowerCase === true && upperCase === true && numerical === true && special === true) {
    //magic happens here

          } else if (lowerCase === false && upperCase === true && numerical === true && special === true) {
            //little less magic here
            
          } else if (lowerCase === true && upperCase === false && numerical === true && special === true){
            //little less magic here

          } else if (lowerCase === true && upperCase === true && numerical === false && special === true){
            //little less magic here

          } else if (lowerCase === true && upperCase === true && numerical === true && special === false){
            //little less magic here

          } else if (lowerCase === true && upperCase === false && numerical === true && special === true){
            //little less magic here

          } else if (lowerCase === false && upperCase === false && numerical === true && special === true){
            //little less magic here

          } else if (lowerCase === false && upperCase === true && numerical === false && special === true){
            //little less magic here

          } else if (lowerCase === false && upperCase === true && numerical === true && special === false){
            //little less magic here

          } else if (lowerCase === true && upperCase === false && numerical === false && special === true){
            //little less magic here

          } else if (lowerCase === true && upperCase === false && numerical === true && special === false){
            //little less magic here

          } else if (lowerCase === true && upperCase === true && numerical === false && special === false){
            //little less magic here

          } else if (lowerCase === false && upperCase === false && numerical === false && special === true){
            //even less magic here

          } else if (lowerCase === false && upperCase === false && numerical === true && special === false){
            //even less magic here

          } else if (lowerCase === false && upperCase === true && numerical === false && special === false){
            //even less magic here

          } else if (lowerCase === true && upperCase === false && numerical === false && special === false){
            //even less magic here

          } else (lowerCase === false && upperCase === false && numerical === false && special === false){
            //no magic here

          }


//then need to push characters to the array
//then need to post result so user can see it on web page